// <auto-generated />
using System;
using FFPP.Data.Logging;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FFPP.Migrations.FfppLogsDbContext_Migrations
{
    [DbContext(typeof(FfppLogsDbContext))]
    [Migration("20220814191043_InitialCreate_FfppLogsDbContext")]
    partial class InitialCreate_FfppLogsDbContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FFPP.Data.Logging.FfppLogsDbContext+LogEntry", b =>
                {
                    b.Property<Guid>("RowKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("API")
                        .HasColumnType("longtext");

                    b.Property<string>("Message")
                        .HasColumnType("longtext");

                    b.Property<bool?>("SentAsAlert")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Severity")
                        .HasColumnType("longtext");

                    b.Property<string>("Tenant")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .HasColumnType("longtext");

                    b.HasKey("RowKey");

                    b.ToTable("_logEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
