// <auto-generated />
using FFPP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FFPP.Migrations.ExcludedTenantsDbContext_Migrations
{
    [DbContext(typeof(ExcludedTenantsDbContext))]
    partial class ExcludedTenantsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FFPP.Data.ExcludedTenantsDbContext+ExcludedTenant", b =>
                {
                    b.Property<string>("TenantDefaultDomain")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DateString")
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .HasColumnType("longtext");

                    b.HasKey("TenantDefaultDomain");

                    b.ToTable("_excludedTenantEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
