// <auto-generated />
using System;
using FFPP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FFPP.Migrations.UserProfilesDbContext_Migrations
{
    [DbContext(typeof(UserProfilesDbContext))]
    partial class UserProfilesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FFPP.Data.UserProfilesDbContext+UserProfile", b =>
                {
                    b.Property<Guid>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int?>("defaultPageSize")
                        .HasColumnType("int");

                    b.Property<string>("defaultUsageLocation")
                        .HasColumnType("longtext");

                    b.Property<string>("identityProvider")
                        .HasColumnType("longtext");

                    b.Property<string>("lastTenantCustomerId")
                        .HasColumnType("longtext");

                    b.Property<string>("lastTenantDomainName")
                        .HasColumnType("longtext");

                    b.Property<string>("lastTenantName")
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .HasColumnType("longtext");

                    b.Property<string>("photoData")
                        .HasColumnType("longtext");

                    b.Property<string>("theme")
                        .HasColumnType("longtext");

                    b.Property<string>("userDetails")
                        .HasColumnType("longtext");

                    b.HasKey("userId");

                    b.ToTable("_userProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
